### ISSUE TITLE
pressing "F1" on selected text causes program to crash

### ISSUE THREAD

**Issue by lw1990** [fincs/SciTE4AutoHotkey#19]
; Issue in AHK syntax for fun
; Steps to reproduce this issue
Run SciTE.exe
WinMenuSelectItem,A,,File,New
WinMenuSelectItem,A,,File,Save ; this step is required!
send, global ; type the word global in the editor
^a ; press Ctrl+A to select the word global
send, {F1} ; try to open "help" for the word global by pressing the F1 hotkey
; The resulting issue is a help window popup which is blank and infinitely tries to load. Upon trying to close this window SciTE.exe crashes.

![image](https://cloud.githubusercontent.com/assets/2457611/11899787/94889d80-a56f-11e5-9075-3cee34d3fb3c.png)

**Comment by smsrkr** [comment]
Open the location of AutoHotkey.chm (that is, the AHK installation folder), and delete/rename AutoHotkey.chw file. This can help.

**Comment by lw1990** [comment]
It did not help, also, why would it?

**Comment by smsrkr** [comment]
> why would it?
Dunno. Did help me once or twice though.

**Comment by joedf** [comment]
My system was recently updated to Windows 10. I think it might be related. Every time I run the Help file directly from SciTE4AHK (either by manually clicking it in the menu or pressing F1) the Help file appears but immediately freezes. I think this is due to some kind of incompatibility of the context sensitive feature towards Windows 10.

That said, I added a :blue_book: icon to my toolbar to `Run, "C:\Program Files\AutoHotkey\AutoHotkey.chm"` directly.

**Comment by CorinthCom** [comment]
This is happening to me to, upgraded to Windows 10 and the F1 Help function crashes most times.
Also after typing a few character in the Help search box crashes the help.
I'm able to save the script and close SciTE4AutoHotkey, which then closes the help window.

**Comment by intellekta** [comment]
This is happening to me to, fresh installed windows 10.
F1 crashes from time to time.
Also after typing a few character in the Help search box crashes the help.

**Comment by fincs** [comment]
[Please try again with the latest release](https://github.com/fincs/SciTE4AutoHotkey/releases/tag/v3.1.0).
